// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AModal: typeof import('ant-design-vue/es')['Modal']
    InstallBanner: typeof import('./src/components/InstallBanner.vue')['default']
    ReloadPWA: typeof import('./src/components/ReloadPWA.vue')['default']
  }
}

export {}
